create table tb_categoria (atualizado_em TIMESTAMP  , criado_em TIMESTAMP  , id bigint NOT NULL AUTO_INCREMENT , nome varchar(255), primary key (id));
create table tb_perfil (id bigint NOT NULL AUTO_INCREMENT , nome varchar(255), primary key (id));
create table tb_produto (preco float(53), atualizado_em TIMESTAMP  , criado_em TIMESTAMP  , id bigint NOT NULL AUTO_INCREMENT, descricao TEXT, img_url varchar(255), nome varchar(255), primary key (id));
create table tb_produto_categoria (id_categoria bigint not null, id_produto bigint not null, primary key (id_categoria, id_produto));
create table tb_usuario (atualizado_em TIMESTAMP  , criado_em TIMESTAMP  , id bigint NOT NULL AUTO_INCREMENT, email varchar(255), nome varchar(255), senha varchar(255), telefone varchar(255), primary key (id));
create table tb_usuario_perfil (id_perfil bigint not null, id_usuario bigint not null, primary key (id_perfil, id_usuario));
alter table tb_produto_categoria add constraint FKqtt9g668uolxpjd42rdb6g7kk foreign key (id_categoria) references tb_categoria(id);
alter table tb_produto_categoria add constraint FKsf16c80ybln49mop4yex7v7pg foreign key (id_produto) references tb_produto(id);
alter table tb_usuario_perfil add constraint FKskwwrm4i1ds1ekvp3vf6jj9h4 foreign key (id_perfil) references tb_perfil(id);
alter table tb_usuario_perfil add constraint FKb82f4fopikpqy2ucxk7osn6y8 foreign key (id_usuario) references tb_usuario(id);
insert into tb_categoria (nome,criado_em) values ('Livros',NOW());
insert into tb_categoria (nome,criado_em) values ('Notebookes',NOW());
insert into tb_categoria (nome,criado_em) values ('Computadores',NOW());
insert into tb_categoria (nome,criado_em) values ('Brinquedos',NOW());
insert into tb_produto (nome,descricao,preco,img_url,criado_em) values ('Brinquedos estrela 01', 'esse brinquedo é eletronico', 30.40, 'http://localhost:8080/estrela01.jpg',NOW());
insert into tb_produto (nome,descricao,preco,img_url,criado_em) values ('Brinquedos estrela 02', 'esse brinquedo é eletronico', 40.40, 'http://localhost:8080/estrela02.jpg',NOW());
insert into tb_produto (nome,descricao,preco,img_url,criado_em) values ('Brinquedos estrela 03', 'esse brinquedo é eletronico', 50.40, 'http://localhost:8080/estrela03.jpg',NOW());
insert into tb_produto (nome,descricao,preco,img_url,criado_em) values ('Brinquedos estrela 04', 'esse brinquedo é eletronico', 60.40, 'http://localhost:8080/estrela04.jpg',NOW());
insert into tb_produto (nome,descricao,preco,img_url,criado_em) values ('Brinquedos estrela 05', 'esse brinquedo é eletronico', 70.40, 'http://localhost:8080/estrela05.jpg',NOW());
insert into tb_produto_categoria(id_produto,id_categoria) values (1,1);
insert into tb_produto_categoria(id_produto,id_categoria) values (1,2);
insert into tb_produto_categoria(id_produto,id_categoria) values (2,1);
insert into tb_produto_categoria(id_produto,id_categoria) values (3,3);